// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbvpnpgtbpmgdxmkcvgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJidnBucGd0YnBtZ2R4bWtjdmdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NDA3MDIsImV4cCI6MjA2NDExNjcwMn0.8cmnpz7zTcJwXlP0VAuak4UdFwqJ_hJAnXyrp7ArpVg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);